name: dockerized-python
services:
  app:
    build:
      context: ./app
      target: development
      args:
        - USERNAME=${USER:?error}
        - PROJECT_ROOT=${PROJECT_ROOT:?error}
    ports:
      - 8000:8000
    working_dir: $PROJECT_ROOT
    pull_policy: build
    develop:
      watch:
        - action: sync
          path: ./app
          target: $PROJECT_ROOT
      #  - action: rebuild
      #    path: ./requirements.txt
